# Generated by Django 3.1.2 on 2020-10-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autolavado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='autos'),
        ),
    ]
