# Generated by Django 3.1.2 on 2020-10-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autolavado', '0002_auto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='autoGaleria',
            fields=[
                ('Nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Imagen', models.ImageField(null=True, upload_to='autosGaleria')),
            ],
        ),
        migrations.CreateModel(
            name='autoInicio',
            fields=[
                ('Nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Imagen', models.ImageField(null=True, upload_to='autosInicio')),
            ],
        ),
        migrations.DeleteModel(
            name='auto',
        ),
    ]
