# Generated by Django 3.1.2 on 2020-10-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autolavado', '0004_misionvision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misionvision',
            name='mision',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='misionvision',
            name='vision',
            field=models.TextField(),
        ),
    ]
