# Generated by Django 3.1.2 on 2020-10-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autolavado', '0005_auto_20201018_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('nombre', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
